//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT_STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT_STATE()
        {
            this.PATIENTS_APPOINTMENTS = new HashSet<PATIENTS_APPOINTMENTS>();
        }
    
        public int Id { get; set; }
        public string State_en { get; set; }
        public string State_ar { get; set; }
    
        public virtual APPOINTMENT_STATE APPOINTMENT_STATE1 { get; set; }
        public virtual APPOINTMENT_STATE APPOINTMENT_STATE2 { get; set; }
        public virtual APPOINTMENT_STATE APPOINTMENT_STATE11 { get; set; }
        public virtual APPOINTMENT_STATE APPOINTMENT_STATE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENTS_APPOINTMENTS> PATIENTS_APPOINTMENTS { get; set; }
    }
}
