//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.DOCTORS_APPOINTMENT_DETAILS = new HashSet<DOCTORS_APPOINTMENT_DETAILS>();
            this.DOCTORS_AVAILABLE = new HashSet<DOCTORS_AVAILABLE>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> specialization { get; set; }
        public Nullable<int> Specialty1 { get; set; }
        public Nullable<int> Specialty2 { get; set; }
        public Nullable<int> Specialty3 { get; set; }
        public string Country { get; set; }
        public Nullable<int> City { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORS_APPOINTMENT_DETAILS> DOCTORS_APPOINTMENT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORS_AVAILABLE> DOCTORS_AVAILABLE { get; set; }
        public virtual SPECIALIZATION SPECIALIZATION1 { get; set; }
        public virtual SPECIALTY SPECIALTY { get; set; }
        public virtual SPECIALTY SPECIALTY4 { get; set; }
        public virtual SPECIALTY SPECIALTY5 { get; set; }
        public virtual CITy CITy1 { get; set; }
    }
}
