//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTORS_AVAILABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTORS_AVAILABLE()
        {
            this.DOCTORS_APPOINTMENT_DETAILS = new HashSet<DOCTORS_APPOINTMENT_DETAILS>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> StartingTime { get; set; }
        public Nullable<System.TimeSpan> EndingTime { get; set; }
        public Nullable<System.TimeSpan> AppointmentDuration { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORS_APPOINTMENT_DETAILS> DOCTORS_APPOINTMENT_DETAILS { get; set; }
    }
}
