//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPECIALTY()
        {
            this.DOCTORS = new HashSet<DOCTOR>();
            this.DOCTORS1 = new HashSet<DOCTOR>();
            this.DOCTORS2 = new HashSet<DOCTOR>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public string Specialty1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORS2 { get; set; }
        public virtual SPECIALIZATION SPECIALIZATION { get; set; }
    }
}
