//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEEK_DAYS
    {
        public int Id { get; set; }
        public string Day_full { get; set; }
        public string Day_short { get; set; }
        public string Day_ar { get; set; }
    }
}
